#!/usr/bin/env python3
"""
Publish the latest run to GitHub Pages.

  - Reads loop/state/last_run.json for run_dir
  - Copies loop/runs/<id>/* → docs/runs/<id>/*
  - Regenerates docs/index.md from all docs/runs/*/VERDICT.md
  - Atomic git add docs/ + commit + push

Designed to be called from `.github/workflows/weekly.yml` after stage_b.py.
Idempotent — safe to re-run; existing copies overwritten.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LOOP = ROOT / "loop"
STATE_FILE = LOOP / "state" / "last_run.json"
DOCS = ROOT / "docs"
DOCS_RUNS = DOCS / "runs"
DOCS_INDEX = DOCS / "index.md"


def log(msg: str) -> None:
    print(f"[publish] {msg}", flush=True)


def run(cmd: list[str], cwd: Path | None = None, check: bool = True) -> str:
    proc = subprocess.run(cmd, cwd=cwd or ROOT, capture_output=True, text=True)
    if check and proc.returncode != 0:
        log(f"CMD FAILED ({proc.returncode}): {' '.join(cmd)}")
        log(f"stderr: {proc.stderr}")
        sys.exit(proc.returncode)
    return proc.stdout.strip()


def parse_verdict(verdict_md: str, run_id: str) -> dict:
    """Pull a small summary out of VERDICT.md for the index row."""
    # Find the first H1 / H2 title
    title = run_id
    m = re.search(r"^#\s+(.+)$", verdict_md, re.MULTILINE)
    if m:
        title = m.group(1).strip()
    # First table row of selectable directions
    selectable_count = 0
    if "Selectable directions" in verdict_md:
        # crude count: number of table rows starting with `| 1 |`, `| 2 |`, etc.
        selectable_count = len(
            re.findall(r"^\|\s*\d+\s*\|", verdict_md, re.MULTILINE)
        )
    # Top direction = first slug in the selectable table
    top_slug = ""
    m = re.search(r"^\|\s*1\s*\|\s*`?([a-z0-9\-]+)`?", verdict_md, re.MULTILINE)
    if m:
        top_slug = m.group(1).strip()
    return {
        "run_id": run_id,
        "title": title,
        "selectable_count": selectable_count,
        "top_slug": top_slug,
    }


def copy_run_to_docs(run_dir: Path, run_id: str) -> Path:
    target = DOCS_RUNS / run_id
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(run_dir, target)
    log(f"copied {run_dir} → {target}")
    return target


def regenerate_index() -> None:
    runs = sorted(
        [p for p in DOCS_RUNS.iterdir() if p.is_dir()],
        key=lambda p: p.name,
        reverse=True,
    )

    rows = []
    summaries = []
    for r in runs:
        verdict_path = r / "VERDICT.md"
        if not verdict_path.exists():
            log(f"  skip {r.name} — no VERDICT.md")
            continue
        try:
            verdict_md = verdict_path.read_text(encoding="utf-8")
            summary = parse_verdict(verdict_md, r.name)
            rows.append(
                f"| [{summary['run_id']}](runs/{summary['run_id']}/VERDICT.md) "
                f"| `{summary['top_slug']}` "
                f"| {summary['selectable_count']} "
                f"| [directions/](runs/{summary['run_id']}/directions/) |"
            )
            summaries.append(summary)
        except Exception as e:
            log(f"  failed to parse {r.name}: {e}")

    # README-style intro + history table
    body = f"""# Opportunity Loop — Weekly Direction Radar

Weekly TrustMRR opportunity scanner. Auto-publishes 3–5 selectable startup
direction packages every Monday morning (Beijing time). Built from the
[`loop/`](../loop/) pipeline; see the project root for the source.

**How to read:** each week's [`VERDICT.md`](runs/{summaries[0]['run_id'] if summaries else 'LATEST'}/VERDICT.md)
lists the selectable directions, ranked. Each `directions/<slug>.md` is a
full PRD + 14-day build plan + 30-day marketing calendar + kill criteria.

**Goal constraints (hard):** $10K MRR · 14-day MVP · ≤$300/30-day marketing.
A direction only ships if its demand ≥ 3 AND competition ≤ 3; otherwise it's
a GO_NARROW (unbundle of a hotter market with explicit wedge) or KILL.

---

## This week

{summaries[0]['title'] if summaries else '_no runs yet_'}

See [`VERDICT.md`](runs/{summaries[0]['run_id'] if summaries else 'LATEST'}/VERDICT.md)
for selectable directions and [`directions/`](runs/{summaries[0]['run_id'] if summaries else 'LATEST'}/directions/)
for full packages.

---

## History

| Run | Top direction | Selectables | Full package |
|---|---|---:|---|
"""
    body += "\n".join(rows) if rows else "| _no runs yet_ | | | |"

    body += f"""

---

_Generated by [`.github/workflows/weekly.yml`](../.github/workflows/weekly.yml).
Last build: {datetime.now(timezone.utc).isoformat()}._
"""

    DOCS_INDEX.write_text(body, encoding="utf-8")
    log(f"regenerated docs/index.md ({len(rows)} runs)")


def git_commit_and_push() -> None:
    run(["git", "config", "user.name", "opportunity-loop-bot"])
    run(["git", "config", "user.email", "actions@users.noreply.github.com"])

    # Stage only docs/ — repo policy is that loop/runs/ is gitignored
    run(["git", "add", "docs/"])

    # Bail early if nothing changed
    diff = run(["git", "diff", "--cached", "--name-only"], check=False)
    if not diff.strip():
        log("no docs/ changes — skipping commit")
        return

    state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    msg = f"weekly: {state['last_run_id']} — {state.get('selectable_count', 0)} selectables"
    run(["git", "commit", "-m", msg])
    log(f"committed: {msg}")

    # Push — set upstream if needed
    push = subprocess.run(
        ["git", "push"], cwd=ROOT, capture_output=True, text=True
    )
    if push.returncode != 0:
        # First-push fallback: set upstream then push
        if "no upstream" in push.stderr or "set upstream" in push.stderr:
            log("no upstream — setting and pushing")
            run(["git", "push", "--set-upstream", "origin", "main"])
        else:
            log(f"push failed: {push.stderr}")
            sys.exit(push.returncode)
    log("pushed to origin/main")


def main() -> None:
    if not STATE_FILE.exists():
        log(f"FATAL: state file missing at {STATE_FILE} — run Stage A first")
        sys.exit(1)

    state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    if state.get("agent_stage") != "done":
        log(
            f"FATAL: agent_stage is '{state.get('agent_stage')}' — run Stage B first"
        )
        sys.exit(1)

    run_dir = (LOOP / state["run_dir"]).resolve()
    if not run_dir.exists():
        log(f"FATAL: run dir missing: {run_dir}")
        sys.exit(1)

    log(f"publishing run {state['last_run_id']}")
    DOCS.mkdir(parents=True, exist_ok=True)
    DOCS_RUNS.mkdir(parents=True, exist_ok=True)

    copy_run_to_docs(run_dir, state["last_run_id"])
    regenerate_index()
    git_commit_and_push()
    log("DONE")


if __name__ == "__main__":
    main()
